apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"